version: '3.6'
# To create this run:
# > docker network create maternity_net
networks:
  maternity_net:
    external: true

services:
  maternity-web-facade:
    build: ../..

    networks:
      - maternity_net

    # Expose port host 8789 for debugging, and 8085 for service
    ports:
      - "8789:8787"
      - "8085:8080"

    environment:
      - LOG_MAX_FILE_SIZE=10MB
      - LOG_MAX_BACKUP_INDEX=5
      # Set oiosaml.home + open debug socket
      - JAVA_OPTS=$JAVA_OPTS -Doiosaml.home=/pack/oiosaml -agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n


    volumes:
      # Logging
      - ./log:/pack/wildfly8/standalone/log/
      # Log4j configuration
      - ../configuration/log4j-maternity.xml:/pack/wildfly8/modules/dk/sds/nsp/maternity/cfg/main/log4j-maternity.xml
      # Slalog configuration
      - ../configuration/log4j-nspslalog.properties:/pack/wildfly8/modules/dk/sds/nsp/maternity/cfg/main/log4j-nspslalog.properties
      # App properties
      - ../configuration/maternity-facade.properties:/pack/wildfly8/modules/dk/sds/nsp/maternity/cfg/main/maternity-facade.properties
      # OIOSaml.java to oiosaml.home
      - ../configuration/oiosaml/localhost-development:/pack/oiosaml
